USE [master]
GO

/****** Object:  Database [royal-library]    Script Date: 1/27/2023 4:43:57 PM ******/
CREATE DATABASE [royal-library]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'royal-library', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DEVENVIROMENT\MSSQL\DATA\royal-library.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'royal-library_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.DEVENVIROMENT\MSSQL\DATA\royal-library_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [royal-library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [royal-library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [royal-library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [royal-library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [royal-library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [royal-library] SET ARITHABORT OFF 
GO

ALTER DATABASE [royal-library] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [royal-library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [royal-library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [royal-library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [royal-library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [royal-library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [royal-library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [royal-library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [royal-library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [royal-library] SET  DISABLE_BROKER 
GO

ALTER DATABASE [royal-library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [royal-library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [royal-library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [royal-library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [royal-library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [royal-library] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [royal-library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [royal-library] SET RECOVERY FULL 
GO

ALTER DATABASE [royal-library] SET  MULTI_USER 
GO

ALTER DATABASE [royal-library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [royal-library] SET DB_CHAINING OFF 
GO

ALTER DATABASE [royal-library] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [royal-library] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [royal-library] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [royal-library] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [royal-library] SET QUERY_STORE = ON
GO

ALTER DATABASE [royal-library] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [royal-library] SET  READ_WRITE 
GO


